apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-12-09T14:17:51Z"
  generation: 1
  labels:
    app: echoserver
  name: echoserver
  namespace: myechoserver
  uid: 306cfa47-a28a-49b0-886e-c3aac6d65938
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echoserver
    spec:
      containers:
      - image: jmalloc/echo-server:dev
        imagePullPolicy: IfNotPresent
        name: echo-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
